### ISSUE TITLE
Preparations

### ISSUE THREAD

**Issue by daviddias** [daviddias/hexagons-ieeextreme#1]
[ ] - Do the examples
[ ] - Create a skelton for exercise (all exercises are stdin -> stdout, it is better if we have our streams thing created)
[ ] - Create folders for each exercise

**Comment by axfcampos** [comment]
Can you link the examples?

**Comment by daviddias** [comment]
@axfcampos here are some of the old - http://www.ieee.org/membership_services/membership/students/awards/xtremesamples.html but now they use hackerrank so any hackerrank code puzzle would be a good practice:

https://www.hackerrank.com/
